# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15registry_server.proto\x12\x04grpc\"+\n\x0fRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"K\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tprimaryIp\x18\x02 \x01(\t\x12\x13\n\x0bprimaryPort\x18\x03 \x01(\x05\">\n\x17\x46\x65tchServerListResponse\x12\x12\n\nserverList\x18\x01 \x03(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x0e\n\x0c\x44ummyRequest2\x91\x01\n\x0eRegistryServer\x12\x39\n\x08Register\x12\x15.grpc.RegisterRequest\x1a\x16.grpc.RegisterResponse\x12\x44\n\x0f\x46\x65tchServerList\x12\x12.grpc.DummyRequest\x1a\x1d.grpc.FetchServerListResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=31
  _REGISTERREQUEST._serialized_end=74
  _REGISTERRESPONSE._serialized_start=76
  _REGISTERRESPONSE._serialized_end=151
  _FETCHSERVERLISTRESPONSE._serialized_start=153
  _FETCHSERVERLISTRESPONSE._serialized_end=215
  _DUMMYREQUEST._serialized_start=217
  _DUMMYREQUEST._serialized_end=231
  _REGISTRYSERVER._serialized_start=234
  _REGISTRYSERVER._serialized_end=379
# @@protoc_insertion_point(module_scope)
