# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x04grpc\"1\n\x0eSimpleResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\";\n\x0cWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"O\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\"\x1b\n\x0bReadRequest\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"_\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\"\x1d\n\rDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"7\n\x16ReplicateDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"U\n\x15ReplicateWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"3\n\x17\x41\x64\x64ReplicaServerRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\xe8\x03\n\x06Server\x12\x30\n\x05Write\x12\x12.grpc.WriteRequest\x1a\x13.grpc.WriteResponse\x12\x37\n\x0cPrimaryWrite\x12\x12.grpc.WriteRequest\x1a\x13.grpc.WriteResponse\x12\x43\n\x0eReplicateWrite\x12\x1b.grpc.ReplicateWriteRequest\x1a\x14.grpc.SimpleResponse\x12-\n\x04Read\x12\x11.grpc.ReadRequest\x1a\x12.grpc.ReadResponse\x12\x33\n\x06\x44\x65lete\x12\x13.grpc.DeleteRequest\x1a\x14.grpc.SimpleResponse\x12:\n\rPrimaryDelete\x12\x13.grpc.DeleteRequest\x1a\x14.grpc.SimpleResponse\x12\x45\n\x0fReplicateDelete\x12\x1c.grpc.ReplicateDeleteRequest\x1a\x14.grpc.SimpleResponse\x12G\n\x10\x41\x64\x64ReplicaServer\x12\x1d.grpc.AddReplicaServerRequest\x1a\x14.grpc.SimpleResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLERESPONSE._serialized_start=22
  _SIMPLERESPONSE._serialized_end=71
  _WRITEREQUEST._serialized_start=73
  _WRITEREQUEST._serialized_end=132
  _WRITERESPONSE._serialized_start=134
  _WRITERESPONSE._serialized_end=213
  _READREQUEST._serialized_start=215
  _READREQUEST._serialized_end=242
  _READRESPONSE._serialized_start=244
  _READRESPONSE._serialized_end=339
  _DELETEREQUEST._serialized_start=341
  _DELETEREQUEST._serialized_end=370
  _REPLICATEDELETEREQUEST._serialized_start=372
  _REPLICATEDELETEREQUEST._serialized_end=427
  _REPLICATEWRITEREQUEST._serialized_start=429
  _REPLICATEWRITEREQUEST._serialized_end=514
  _ADDREPLICASERVERREQUEST._serialized_start=516
  _ADDREPLICASERVERREQUEST._serialized_end=567
  _SERVER._serialized_start=570
  _SERVER._serialized_end=1058
# @@protoc_insertion_point(module_scope)
